### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'publish'

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/fedora-messaging#212]
Plenty of test started failing on Anitya with fedora-messaging 2.0.0 with the error in title.

Here is the link for the travis job, so you can look at the logs: https://travis-ci.org/release-monitoring/anitya/builds/624136745

Locally I have fedora-messaging 1.7.2 and this issue didn't happened.

**Comment by abompard** [comment]
Thanks for reporting, I've opened PR #213 to fix the error.

However, a lot of your unit test code is currently not calling `fedora_messaging.testing.mock_send()`, therefore your tests are delayed because Fedora Messaging tries to send messages to a non-existant RabbitMQ, and tries to reconnect periodically until it hits the publishing timeout. I'll send you a PR to fix that.

**Comment by Zlopez** [comment]
I know that some tests sending fedora messages are not calling `mock_send()`. I should've fix this some time ago, but didn't found time. :-(
