### ISSUE TITLE
Add the metadata for FMN in the headers

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fedora-messaging#27]
The new FMN will leverage RabbitMQ's header exchange feature to distribute relevant message in user-specific queues, that would then be distributed by IRC or email.

To use the header exchange, we need the following data in the headers:
* RPM package name that is affected by the action
* FAS username(s) of the user(s) who is/are affected by the action

We could add the username who did the action, but I'm not sure that's really useful. Why would you want to be notified of actions you take, after all? I could be useful for mentoring, though.

The header exchange in RabbitMQ [only does string matching](https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchange-headers), and there can be multiple users affected by a message. A header won't be matched if it's a list, and there can't be multiple headers with the same key.
It does not appear that we'll be able to entirely rely on RabbitMQ's header routing, and avoid a custom daemon. Am I missing something?

In any case, the base `Message` class must have 2 accessors, `package` and `affected_usernames` (names to be debated) that would return `None` and an empty list by default, and that publishers can override.

**Comment by pypingou** [comment]
> package and affected_usernames (names to be debated)

To start up the debate (and because the rest of the ticket sounds very sane to me as an outsider), I'd consider using `affected_packages` (or w/o the s at the end if desired) and `affected_usernames` to be consistent.

**Comment by abompard** [comment]
@pypingou: Yeah I was considering going with `usernames` actually because that's what we have currently in fedmsg-meta.

Another comment: I have found a couple places where multiple packages are associated with a message: at least Bodhi and Anitya. It feels like we should thus have a `packages` accessor that would return a list, and abandon the idea of using the header exchange. Since we would have to write a routing daemon anyway, it would be more work to setup the routing with RabbitMQ (and update the bindings when a user's watch list changes) only for packages than to add a `packages` accessor and act on it.

What do you think?

**Comment by jeremycline** [comment]
I had a scheme to make the header exchange work, but I do need to confirm one thing before I know if it works.

The idea is that authors would provide ``affected_{usernames,packages}`` accessors (along with a few other settings for a message, like importance) and we could add something in the library to use those to create workable headers.

For example, suppose the ``affected_packages`` is ``['kernel', 'kernel-headers', 'kernel-tools']``, we take that and add the following headers:
```
{
    'fedora_messaging_packages_kernel': True,
    'fedora_messaging_packages_kernel_headers': True,
    'fedora_messaging_packages_kernel_tools': True,
}
```
A user can then specify they want any messages that reference one of a list of packages, and we turn that into a header binding for any of those packages prefixed with 'fedora_messaging_packages'. Same deal with users.

One thing I'm not sure about is if "any messages that are about the kernel package AND importance=high" will work. Does the ALL header binding require the headers to match exactly, or can the ones I specify be a subset of the total headers? If that doesn't work we will need a shim service to transform the message topic/headers and republish them before notifications handles them.

**Comment by abompard** [comment]
I'm not sure I understand this. In [the headers exchange docs](https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchange-headers) they mention a `x-match` header that you can set to `any` or `all` if you have multiple headers in your bindings.

There's apparently no risk we hit a limit to the headers size since [the headers table can contain 4 billion entries](https://stackoverflow.com/questions/30716002/is-there-a-size-limit-on-a-rabbitmq-message-header) (even though there's a performance hit)

I'm still unsure that setting up and updating the bindings is going to be easier than a daemon that would do the routing. What happens when user alice adds a new package, for example. We need to subscribe to that event and update her bindings, right?
If it's a daemon, it can also route to only two queues, one for email and one for IRC, that two other daemons would consume, and not one queue per user as with the header exchange, that those daemons would all have to subscribe to (and add new subscriptions when new users are registered, etc).

**Comment by jeremycline** [comment]
> If it's a daemon, it can also route to only two queues, one for email and one for IRC, that two other daemons would consume, and not one queue per user as with the header exchange, that those daemons would all have to subscribe to (and add new subscriptions when new users are registered, etc).

One motivation for the one-queue-per-user approach is it makes batching messages into digests trivial. Otherwise you have to do what FMN is doing now, which is dropping messages that are destined for people who want batching into a separate queue (or the database, in FMN's case). With the queue per user approach, everything is the same, it's just some queues have consumers all the time, and some have a Twisted call loop at an interval applied to them in the sending daemon.

Another reason I thought the one-queue-per-user approach would be good is that RabbitMQ's job is to quickly route messages and hold them in queues, so if we constrained ourselves to things it can route, notifications will be very fast.

It's definitely not a clear-cut situation. As you pointed out, you need something to keep the bindings up-to-date. To me, though, that feels like an easier task than doing the routing and batch queuing ourselves. And if we're not going to offer a batching feature (although I think it is fairly widely used), things get easier with the 2 queue based approach.

I'd really like to make a PoC of my plan before seriously pitching it, though. Whatever direction we go, I think we can safely add the metadata in the library populated from standard accessors from https://github.com/fedora-infra/fedora-messaging/issues/28.
