### ISSUE TITLE
Does message priority needs to be explicitly set in config?

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/fedora-messaging#278]
In https://github.com/fedora-infra/fedora-messaging/blob/4228dd827416ab46fbad56b1521bf4d2f8db284e/fedora_messaging/message.py#L297-L298 it is said that priority defaults to zero, but https://github.com/fedora-infra/fedora-messaging/blob/4228dd827416ab46fbad56b1521bf4d2f8db284e/fedora_messaging/message.py#L362 needs a value to be explicitly set in the config file...

I've found robosignatory tests started to fail on this and filed a [PR](https://pagure.io/robosignatory/pull-request/55) to correct tests, but I'm unsure if this has to be fixed here rather than there.

**Comment by abompard** [comment]
Actually the configuration object has a default value set:

https://github.com/fedora-infra/fedora-messaging/blob/4228dd827416ab46fbad56b1521bf4d2f8db284e/fedora_messaging/config.py#L335

So this should be optional in the configuration file. The robosig tests fail probably because they are mocking the config object entirely. You could try to use `mock.patch.dict` instead of just `mock.patch`.

**Comment by mattiaverga** [comment]
With `mock.patch.dict` tests seem to be happy again, thanks.
